//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawnaThai_Eiei.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShawnaThai_DB_Azure_V3Entities : DbContext
    {
        public ShawnaThai_DB_Azure_V3Entities()
            : base("name=ShawnaThai_DB_Azure_V3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address_Coop> Address_Coop { get; set; }
        public virtual DbSet<AddressFarmer> AddressFarmers { get; set; }
        public virtual DbSet<Admin_Cooperative> Admin_Cooperative { get; set; }
        public virtual DbSet<Cooperative> Cooperatives { get; set; }
        public virtual DbSet<Farmer> Farmers { get; set; }
        public virtual DbSet<History_Sell> History_Sell { get; set; }
        public virtual DbSet<Product_Rice> Product_Rice { get; set; }
        public virtual DbSet<RiceType> RiceTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
