//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawnaThai_Eiei.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Rice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Rice()
        {
            this.History_Sell = new HashSet<History_Sell>();
        }
    
        public string ProD_IDSell { get; set; }
        public string ProD_Pic { get; set; }
        public string ProD_Moisture { get; set; }
        public string ProD_Weight { get; set; }
        public string ProD_Price { get; set; }
        public string ProD_CertiWeightRice { get; set; }
        public string RType_NID { get; set; }
        public string Farmer_IDCard { get; set; }
    
        public virtual Farmer Farmer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_Sell> History_Sell { get; set; }
        public virtual RiceType RiceType { get; set; }
    }
}
